# This is a generated file. Not intended for manual editing.
services:
  app:
    build:
      context: "C:\\Users\\pounce\\Downloads\\HttpServer"
      dockerfile: "Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/HttpServer.dll"
    environment:
      DOTNET_ENVIRONMENT: "Development"
    image: "httpserver:dev"
    ports: []
    volumes:
    - "C:\\Users\\pounce\\Downloads\\HttpServer\\HttpServer:/app:rw"
    - "C:\\Users\\pounce\\Downloads\\HttpServer:/src:rw"
    - "C:\\Users\\pounce\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
